// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using time_tracking.DataAccess;

#nullable disable

namespace time_tracking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230522224600_addBDtsks")]
    partial class addBDtsks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("time_tracking.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = new Guid("380bce50-227c-42ee-8b01-13e0489ca9f8"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2569),
                            ProjectName = "Проект 1",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2588)
                        },
                        new
                        {
                            Id = new Guid("cec4bf27-3f72-4c85-a63b-f5088e069de2"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2590),
                            ProjectName = "Проект 2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2590)
                        },
                        new
                        {
                            Id = new Guid("63635bcf-e75d-4790-bb4a-bf714ddfab6a"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2591),
                            ProjectName = "Проект 3",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2592)
                        },
                        new
                        {
                            Id = new Guid("cfb9ee4d-a11e-4148-aa19-866d3c363c57"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2593),
                            ProjectName = "Проект 4",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2594)
                        });
                });

            modelBuilder.Entity("time_tracking.Models.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TasksName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66d8b04c-8e42-420c-938c-438dae31a7d4"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2872),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2868),
                            ProjectId = new Guid("380bce50-227c-42ee-8b01-13e0489ca9f8"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2873),
                            TasksName = "задача 1",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2872)
                        },
                        new
                        {
                            Id = new Guid("9d61423d-8f1b-4c4d-975d-b3105fefa68b"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2877),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2875),
                            ProjectId = new Guid("380bce50-227c-42ee-8b01-13e0489ca9f8"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2877),
                            TasksName = "задача 2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2876)
                        },
                        new
                        {
                            Id = new Guid("d7b8d698-20c1-4612-bd7e-f45ffe55564a"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2890),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2888),
                            ProjectId = new Guid("cec4bf27-3f72-4c85-a63b-f5088e069de2"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2890),
                            TasksName = "задача 1_2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2889)
                        },
                        new
                        {
                            Id = new Guid("648cf344-4c98-435b-9dcf-188e5417285a"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2894),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2892),
                            ProjectId = new Guid("cec4bf27-3f72-4c85-a63b-f5088e069de2"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2894),
                            TasksName = "задача 2_2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2893)
                        },
                        new
                        {
                            Id = new Guid("40542c88-9685-4577-b691-985ce9be3e74"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2897),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2896),
                            ProjectId = new Guid("380bce50-227c-42ee-8b01-13e0489ca9f8"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2898),
                            TasksName = "задача 1_3",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2897)
                        },
                        new
                        {
                            Id = new Guid("5a79a37c-31f5-4167-aa6d-4a443e407d55"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2901),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2900),
                            ProjectId = new Guid("63635bcf-e75d-4790-bb4a-bf714ddfab6a"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2902),
                            TasksName = "задача 2_3",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2900)
                        },
                        new
                        {
                            Id = new Guid("cda9b165-1318-409a-8293-48836fa61519"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2904),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2903),
                            ProjectId = new Guid("cfb9ee4d-a11e-4148-aa19-866d3c363c57"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2905),
                            TasksName = "задача 1_4",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2904)
                        },
                        new
                        {
                            Id = new Guid("c583be53-aeda-45f3-9254-a7bbdc2b3763"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2908),
                            CreateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2906),
                            ProjectId = new Guid("cfb9ee4d-a11e-4148-aa19-866d3c363c57"),
                            StartDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2908),
                            TasksName = "задача 2_4",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 46, 0, 60, DateTimeKind.Local).AddTicks(2907)
                        });
                });

            modelBuilder.Entity("time_tracking.Models.TasksComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CommentType")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TasksComments");
                });
#pragma warning restore 612, 618
        }
    }
}
