// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using time_tracking.DataAccess;

#nullable disable

namespace time_tracking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("time_tracking.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f656964-f8e9-4e4b-8d19-8a0106e70b96"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6019),
                            ProjectName = "Проект 1",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            Id = new Guid("f1725f3e-3c53-4e22-87ab-207d73399b95"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6032),
                            ProjectName = "Проект 2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6032)
                        },
                        new
                        {
                            Id = new Guid("bd3792ee-cbbb-4d61-81c0-9968c6759356"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6033),
                            ProjectName = "Проект 3",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6034)
                        },
                        new
                        {
                            Id = new Guid("ea604709-b5ad-4b6a-99aa-d351bd714df8"),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6035),
                            ProjectName = "Проект 4",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6035)
                        });
                });

            modelBuilder.Entity("time_tracking.Models.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TasksName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e77e1961-b3a3-48ec-99bf-9b55edda4ce3"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6140),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6139),
                            ProjectId = new Guid("2f656964-f8e9-4e4b-8d19-8a0106e70b96"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6140),
                            TasksName = "задача 1",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6139)
                        },
                        new
                        {
                            Id = new Guid("038e08f6-a053-4d3a-95dd-7ff4b4b9a90f"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6143),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6142),
                            ProjectId = new Guid("2f656964-f8e9-4e4b-8d19-8a0106e70b96"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6144),
                            TasksName = "задача 2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6143)
                        },
                        new
                        {
                            Id = new Guid("d1a2d1d3-baca-471b-82fb-779d478b722a"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6146),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6145),
                            ProjectId = new Guid("f1725f3e-3c53-4e22-87ab-207d73399b95"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6146),
                            TasksName = "задача 1_2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6145)
                        },
                        new
                        {
                            Id = new Guid("166c7718-cc5c-4627-b658-29b9cf7de57c"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6148),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6148),
                            ProjectId = new Guid("f1725f3e-3c53-4e22-87ab-207d73399b95"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6149),
                            TasksName = "задача 2_2",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6148)
                        },
                        new
                        {
                            Id = new Guid("dc85494a-9d3d-4182-995b-ceb853b3ebf0"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6151),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6150),
                            ProjectId = new Guid("bd3792ee-cbbb-4d61-81c0-9968c6759356"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6151),
                            TasksName = "задача 1_3",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6150)
                        },
                        new
                        {
                            Id = new Guid("69ec4aa2-eab0-48b1-950a-17f4d113bb7e"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6153),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6153),
                            ProjectId = new Guid("bd3792ee-cbbb-4d61-81c0-9968c6759356"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6154),
                            TasksName = "задача 2_3",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6153)
                        },
                        new
                        {
                            Id = new Guid("ffbada9e-10d6-428d-9285-6b29e91bd48d"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6156),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6155),
                            ProjectId = new Guid("ea604709-b5ad-4b6a-99aa-d351bd714df8"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6156),
                            TasksName = "задача 1_4",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6156)
                        },
                        new
                        {
                            Id = new Guid("aca626c9-0e21-488f-ba3e-b045671e98a9"),
                            CancelDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6159),
                            CreateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6158),
                            ProjectId = new Guid("ea604709-b5ad-4b6a-99aa-d351bd714df8"),
                            StartDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6159),
                            TasksName = "задача 2_4",
                            UpdateDate = new DateTime(2023, 5, 23, 5, 48, 20, 1, DateTimeKind.Local).AddTicks(6158)
                        });
                });

            modelBuilder.Entity("time_tracking.Models.TasksComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CommentType")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TasksComments");
                });
#pragma warning restore 612, 618
        }
    }
}
